name: pre-commit

on:
    pull_request:
    push:
        branches: [dev]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '3.1.x'
            - uses: pre-commit/action@v2.0.0
